@startuml

class Cliente {
    - nombre: str
    - direccion: str
}

class Orden {
    - fecha: date
    - estado: str
    + caclImpuesto(): impuesto
    + caclTotal(): Total 
    + caclPesoTotal(): PesoTotal
}

class Pago {
    - monto: int
}

class Credito {
    - monto: int
    - fecha: date
    - numero: int
    - tipo: str
}

class Efectivo {
    - monto: int
    - moneda: int
}

class Cheque {
    - monto: int
    - nombre: str
    - identifBanco: int
}

class DetalleOrden {
    - cantidad: int
    - tipoImpuesto: str
    + caclSubtotal(precioPorCantidad, cantidad): Subtotal
    + caclPeso(peso): Peso
}

class Item {
    - peso: int
    - descripcion: str
    + precioPorCantidad(): int
    + obtenerPeso(peso): int
}


Cheque "1" -- "1" Pago : Hereda >
Efectivo "1" -- "1" Pago : Hereda >
Credito "1" -- "1" Pago : Hereda >
Orden "1" -- "*" Pago : Transmiten
Cliente "1" -- "0" Orden : Ejecuta
DetalleOrden "*" -- "1" Orden : Recibe >
Item "1" -- "1" DetalleOrden: Recibe >

@enduml