@startuml  
class EmpresaLista {  
    - empleados: List<Empleado>  
    - tareas: List<Tareas>
    + agregar_tareas(Tarea):
    + agregar_empleado(Empleado)
    + asignar_tarea():
    + procesar_tareas():
}  

class Empleado {  
    - codigo: int 
    - nombre: str
    - genero: str 
    - cantidadTareas: int  
    - colaTareas: List<Tarea>  
    + agregar_tarea(Tarea):  
}  


class Tarea {
    - area_solicitante: str
    - descripcion: str 
    + mostrar_tarea():
}

EmpresaLista "1" -- "1..*" Empleado : contiene >  
Empleado "1" -- "1..*" Tarea : tiene >  
@enduml  