@startuml

class Votante {
    - DNI: int
    - Nombre: str
    - Codigo_lugar_votacion: str
    - Mesa: str
}

class Provincia {
    - nombre: str
    - lista_votantes: list
    + agregar_votantes: Votante
}

class Lugar {
    - codigo_lugar_votacion: str
    - direccion: str 
    - localidad: str
}


class PadronElectoral {
    - fecha: Fecha
    - lista_provincias: List<Provincia>
    - lista_lugares: List<Lugar>
    + agregar_provincia(Provincia):
    + agregar_lugar_votacion(Lugar):
    + consultar_lugar_votacion( provincia, dni_votante, lista_lugares):
}

class Fecha {
    - Año: date
    - Mes: date
    - Dia: date
}

PadronElectoral "1" -- "1" Fecha: Tiene >
PadronElectoral "1" -- "1..*" Lugar : Contiene >
PadronElectoral "1" -- "1..*" Provincia : Contiene >
Provincia "1" -- "1..*" Votante: Contiene >

@enduml



