@startuml

class Votante {
    - DNI: int
    - Nombre: str
    - Codigo_lugar_votacion: str
    - Mesa: str
}

class Provincia {
    - Nombre: str
    - Lista_votantes: list
    + agregar_votantes: Votante
}

class Lugar {
    - Codigo_lugar_votacion: str
    - Direccion: str 
    - Localidad: str
}


class PadronElectoral {
    - fecha_actualizacion: Fecha
    - lista_provincias: List<Provincia>
    - lista_lugares: List<Lugar>
    + agregar_provincias(Provincia):
    + agregar_lugar_votacion(Lugar):
    + buscar_lugar(codigo): str
    + consultar_lugar_votacion(provincia_nombre, dni): str, int
}

class Fecha {
    - Año: date
    - Mes: date
    - Dia: date
}

PadronElectoral "1" -- "1" Fecha: Tiene >
PadronElectoral "1" -- "*" Lugar : Contiene >
PadronElectoral "1" -- "*" Provincia : Contiene >
Provincia "1" -- "1..*" Votante: Contiene >

@enduml



